
spring.datasource.url=jdbc:postgresql://localhost:9092/elearning_db
spring.datasource.username=postgres
spring.datasource.password=yourSuperSecurePassword
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port = 8900

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
spring.web.error.include-message=always
logging.level.org.hibernate.orm.jdbc.bind=trace
spring.jackson.deserialization.fail-on-unknown-properties=true

jwt.secret-key=Z3Vpc3RyaW5nYmsdFzZTY0c2VjcmV0a2Vade5Zm9ybXllbGVhcm5pbmdhcHBsaWbaewNhdGlvbjIwMjY=
jwt.access-token-expiration=900000


