
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=${PORT:8900}

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

spring.web.error.include-message=always

jwt.secret-key=${JWT_SECRET}
jwt.access-token-expiration=900000

ADMIN_EMAIL=admin@elearning.com
ADMIN_PASSWORD=SuperSecurePassword


